### ISSUE TITLE
CSS to reduce width of dump element

### ISSUE THREAD

**Issue by JamoCA** [kwaschny/cf_dump#12] opened 2023-03-13 16:22 UTC
One of the layout differences that I notice with cf_dump compared to Adobe's CFDump/writedump (and Lucee's dump) is the full-width block output of data. The built-in functions render the content using a table which only extends to the width to the longest text value or label or the parent container width (whichever comes first).

You can achieve a similar inline block by changing the `display` property of the `.cf_dump` element. (I've been manually adding this style to projects where I use cf_dump.)

```css
.cf_dump {display: table;}
```
![cf-dump-width-20230313092043](https://user-images.githubusercontent.com/1112671/224763160-237db703-4916-4f2b-a9bb-647035615fc2.png)

**Comment by kwaschny** [comment] 2023-03-14 23:31
I remember having issues with nested elements when using table rendering in some cases. It's basically a hack that will leave it up to the browser how to calculate inline blocks and the resulting total width.

**Comment by JamoCA** [comment] 2023-03-15 00:00
Hmm... I'd be interested to know the use case that caused the problem.  I'll continue testing with some other types of dumps to see if I can identify problems.

**Comment by kwaschny** [comment] 2023-03-19 17:28
So I tested this again and and I haven't been able to reproduce any width/overflow related problems. So either this has been fixed long ago due to a related style change or moving to inline styles has solved it. Either way, I also much prefer the more narrow look. Thanks for the suggestion. 👍

**Closed as completed** 2023-06-01 21:59 UTC
Labels: solution available
